// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data.EF;

namespace Store.Data.EF.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20220611180759_AddNewBooks")]
    partial class AddNewBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Store.Data.BookDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "D. Knuth",
                            Description = "Knuth began the project, originally conceived as a single book with twelve chapters, in 1962. The first three volumes of what was then expected to be a seven-volume set were published in 1968, 1969, and 1973. Work began in earnest on Volume 4 in 1973, but was suspended in 1977 for work on typesetting prompted by the second edition of Volume 2. Writing of the final copy of Volume 4A began in longhand in 2001, and the first online pre-fascicle, 2A, appeared later in 2001.[1] The first published installment of Volume 4 appeared in paperback as Fascicle 2 in 2005.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/6/62/ArtOfComputerProgramming.jpg",
                            Isbn = "ISBN0201038013",
                            Price = 690m,
                            Title = "Art of Programming, Vol. 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "M. Fowler",
                            Description = "As the application of object technology--particularly the Java programming language--has become commonplace, a new problem has emerged to confront the software development community. Significant numbers of poorly designed programs have been created by less-experienced developers, resulting in applications that are inefficient and hard to maintain and extend. Increasingly, software system professionals are discovering just how difficult it is to work with these inherited, \"non - optimal\" applications. For several years, expert-level object programmers have employed a growing collection of techniques to improve the structural integrity and performance of such existing software programs. Referred to as \"refactoring,\" these practices have remained in the domain of experts because no attempt has been made to transcribe the lore into a form that all developers could use",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/51k+BvsOl2L._SX392_BO1,204,203,200_.jpg",
                            Isbn = "ISBN0201454816",
                            Price = 450m,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 3,
                            Author = "B. W. Kernighan, D. M. Ritchie",
                            Description = "The authors present the complete guide to ANSI standard C language programming. Written by the developers of C, this new version helps readers keep up with the finalized ANSI standard for C while showing how to take advantage of C's rich set of operators, economy of expression, improved control flow, and data structures. The 2/E has been completely rewritten with additional examples and problem sets to clarify the implementation of difficult language constructs. For years, C programmers have let K&R guide them to building well-structured and efficient programs. Now this same help is available to those working with ANSI compilers. Includes detailed coverage of the C language plus the official C language reference manual for at-a-glance help with syntax notation, declarations, ANSI changes, scope rules, and the list goes on and on.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/The_C_Programming_Language%2C_First_Edition_Cover.svg/1200px-The_C_Programming_Language%2C_First_Edition_Cover.svg.png",
                            Isbn = "ISBN0131101633",
                            Price = 350m,
                            Title = "C Programminh Language"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Лоран Гунель",
                            Description = "Всесвітньо відомий бестселер Amazon, який вже планують екранізувати, - книга «Бог завжди подорожує інкогніто» українською мовою тепер вийшла у видавництві «Клуб Сімейного Дозвілля»! Алан Грінмор — пересічний молодий чоловік. Він має вельми непогану роботу, яка, втім, його дратує, а нещодавно зненацька його кинула кохана дівчина. Життя здається сірим та безнадійним. Лише один крок відділяє його від стрибка з Ейфелевої вежі, коли один загадковий незнайомець рятує його від смерті. Відтепер між ними укладена угода — на знак вдячності за спасіння, Алан обіцяє виконувати різноманітні завдання, які дивовижним чином змінюють його життя. Тепер він краще розуміє колег, мотиви вчинків оточуючих і щиро переймається проблемами власної компанії. Але ким був той загадковий незнайомець?",
                            Image = "https://img.yakaboo.ua/media/catalog/product/cache/1/image/546x/c239772940bfb0468bd568cd18249fe5/i/m/img293_42.jpg",
                            Isbn = "ISBN0131139671",
                            Price = 180m,
                            Title = "Бог завжди подорожує інкогніто"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Джордж Орвелл",
                            Description = "«1984». Книга, про яку багато говорили колись - і багато говорять зараз. Книга, що стала своєрідним «антифоном» для другої великої антиутопії XX ст. - «Прекрасний новий світ» Олдоса Гакслі. Що, по суті, страшніше - доведене до абсолюту «суспільство споживання» чи доведене до абсолюту «суспільство ідеї»? За Орвеллом, немає і не може бути нічого гіршого тотальної несвободи... \"Ферма тварин\". Гумор. Сарказм. Притча, яка змогла прийняти форму «іронічної антиутопії». Чи може скромна ферма стати символом тоталітарного суспільства? Звісно так. Але... яким побачать це суспільство його «громадяни» - тварини, приречені на бойню?",
                            Image = "https://img.yakaboo.ua/media/catalog/product/cache/1/image/546x/c239772940bfb0468bd568cd18249fe5/i/m/img_49791.jpg",
                            Isbn = "ISBN0131401655",
                            Price = 185m,
                            Title = "Книга 1984. Скотный двор"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Роальд Дал",
                            Description = "Всем поклонникам творчества суперпопулярной Джоан Роулинг, без сомнения, будет интересно познакомиться с этой книгой, автора которой, Роальда Дала, принято считать «литературным отцом» знаменитой писательницы. Хотя, возможно, этот сюжет вам уже знаком, ведь «Чарли и шоколадная фабрика» - самая популярная книга Дала. Бедному мальчику, на каждый день рождения получавшему в подарок лишь маленький шоколадный батончик, предстоит удивительное приключение, ведь его доброта служит примером для других, а добро всегда получает свою награду.",
                            Image = "https://img.yakaboo.ua/media/catalog/product/cache/1/image/546x/c239772940bfb0468bd568cd18249fe5/5/3/53225_28767120.jpg",
                            Isbn = "ISBN0187259640",
                            Price = 175m,
                            Title = "Книга Чарлі і шоколадна фабрика"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Анджей Сапковський",
                            Description = "Біловолосий відьмак Ґеральт із Рівії, один з небагатьох представників колись численного цеху захисників людської раси від породжень нелюдського зла, мандрує невеликими королівствами, які можна охопити поглядом з вежі замку, та великими містами, отримуючи платню за те, чого навчений, - знищення віїв і з'ядарок, стриґ та віпперів. Але є у відьмака і власний кодекс, у якому вбивство - це лише крайня міра, а життя розумне, чим би воно не було, - це все-таки життя. Саме цим він наживає собі нових ворогів, але й знаходить друзів, які колись змінять його долю.",
                            Image = "https://img.yakaboo.ua/media/catalog/product/cache/1/image/546x/c239772940bfb0468bd568cd18249fe5/6/1/616607_front.jpg",
                            Isbn = "ISBN0119456822",
                            Price = 210m,
                            Title = "Книга Відьмак. Останнє бажання. Книга 1"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Анджей Сапковський",
                            Description = "Тепер Ґеральт знає, що таке кохання, знає, що він здатен на людські почуття і на найбільшу самопожертву… У його житті з’являється маленька зеленоока Цірі. На королівства, які століттями воювали лише за перенесення межових знаків, нападає страшний ворог із-за південних гір. І відьмаку все одно: чия ллється кров — людей, дріад чи ельфів…",
                            Image = "https://img.yakaboo.ua/media/catalog/product/cache/1/image/546x/c239772940bfb0468bd568cd18249fe5/3/7/37390_67365.jpg",
                            Isbn = "ISBN0556639788",
                            Price = 210m,
                            Title = "Книга Відьмак. Меч призначення"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Анджей Сапковський",
                            Description = "Героїчна сага Анджея Сапковського про відьмака Ґеральта посідає четверте місце за накладами у Польщі, нагороджена преміями імені Януша Зайделя, преміями SFinks, а 2010 року автор отримав почесну нагороду Європейського співтовариства наукової фантастики EuroCon «Ґранд Майстер». Маленька Цірі — дитя-несподіванка — стала більшою несподіванкою, ніж видавалось спочатку. Жахливі сни про загибель Цінтри руйнують її душу, а чаклунський дар, що народжується, може зруйнувати тіло. Дати йому раду під силу лише могутній чарівниці Йеннефер. Тож Ґеральту не вдається довго переховувати Цірі у Відьмачому Оселищі.",
                            Image = "https://img.yakaboo.ua/media/catalog/product/cache/1/image/546x/c239772940bfb0468bd568cd18249fe5/3/8/38505_57981_1.jpg",
                            Isbn = "ISBN1302795771",
                            Price = 210m,
                            Title = "Книга Відьмак. Кров ельфів. Книга 3"
                        });
                });

            modelBuilder.Entity("Store.Data.OrderDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("money");

                    b.Property<string>("DeliveryUniqueCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PaymentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentServiceName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Store.Data.OrderItemDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Store.Data.OrderItemDto", b =>
                {
                    b.HasOne("Store.Data.OrderDto", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Store.Data.OrderDto", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
